services:
  jekyll-site:
    build: .
    image: jekyll-site
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - JEKYLL_ENV=docker
    # user: 1000:1000  <-- Commented this out to fix the file-writing permission issue